//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstudoEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bairro
    {
        public Bairro()
        {
            this.Cliente = new HashSet<Cliente>();
        }
    
        public int pk_intCod { get; set; }
        public string strNOME { get; set; }
        public string strcep { get; set; }
    
        public virtual ICollection<Cliente> Cliente { get; set; }
    }
}
